### ISSUE TITLE
Branding DocumentCSS

### ISSUE THREAD

**Issue by ramblinjan** [bitovi/documentcss#1]
Replaces issue in [DocumentJS](https://github.com/bitovi/documentjs/issues/129).

Need a DocumentCSS logo for standalone site.

**Comment by ramblinjan** [comment]
@adrifolio or @lkodai any chance one of y'all will have time to work on this in the nearish future? I imagine we could reuse the DocumentJS logo almost entirely (only changing the text and color).

**Comment by adrifolio** [comment]
Definitely! I would like to tackle this in the next couple of weeks.
