### ISSUE TITLE
Need to create a "Getting Started" page

### ISSUE THREAD

**Issue by adrifolio** [bitovi/documentcss#10]
Currently the "Get Started" link on the homepage takes to: http://documentcss.com/docs/index.html, but this page is written with the context of DocumentJS. 

The "get started" page should explain how to get DocumentCSS working in a brief way and then offer links to information on how to configure and customize.

**Comment by ramblinjan** [comment]
Closed by 99624c9414a5a9c454ab0c12cc1cc1ea920453c8

**Comment by adrifolio** [comment]
@jandjorgensen you fix looks good. However I would like to still create a page that gives instructions to quickly get DocumentCSS running. I think that as a designer when shopping or a LSG generator you want to give a quick try and see if it fits your needs, before getting into too much detail. That being said can we keep this issue open? I can work on a draft and share for input.

**Comment by ramblinjan** [comment]
Sure! Would love if you could do a draft.

**Comment by ramblinjan** [comment]
Closing for now (http://documentcss.com/docs/index.html)
Improvements can go in a new issue
