### ISSUE TITLE
DocumentJS link in navbar shouldn't be https

### ISSUE THREAD

**Issue by marshallswain** [bitovi/documentcss#15]
The DocumentJS link in the top navbar is pointing to **HTTPS**://documentjs.com, so it doesn't work.
![screen shot 2015-09-03 at 4 13 50 pm](https://cloud.githubusercontent.com/assets/128857/9671217/e3a79a9a-5256-11e5-9931-95d705c7a584.jpg)

**Comment by gabrielhpugliese** [comment]
:+1:

**Comment by marshallswain** [comment]
Fixed. https://github.com/bitovi/documentcss/blob/master/theme/templates/layout.mustache
