### ISSUE TITLE
Add Quickstart Guide to the dropdown menu

### ISSUE THREAD

**Issue by lkodai** [bitovi/documentcss#32]
![](https://cloud.githubusercontent.com/assets/326843/15896214/ebe63cbe-2d54-11e6-8b80-09d9f43292d3.png)

That dropdown is hardcoded on the index page I believe

**Comment by leoj3n** [comment]
Looks like this has been fixed:

![image](https://cloud.githubusercontent.com/assets/990216/23827786/7210f53a-0681-11e7-81d2-51bde61b1274.png)

So, I think this issue can be closed.
