### ISSUE TITLE
Update guides to use @styles vs @style

### ISSUE THREAD

**Issue by adrifolio** [bitovi/documentcss#40]
@styles is the correct syntax and needs to be updated in a few locations.

**Comment by leoj3n** [comment]
Are you speaking of:

- https://github.com/bitovi/documentcss/blob/master/docs/use.html#L204
- https://github.com/bitovi/documentcss/blame/master/pages/guides/use.md#L30

Those were the only instances I could find of just `@style`.

**Comment by tomgreever** [comment]
@leoj3n yeah, I think we just wanted someone to look it over and find any that were out there. If I remember, we noticed one case and thought it would be good to do a search and replace.
