### ISSUE TITLE
@font warning message

### ISSUE THREAD

**Issue by herrjosua** [bitovi/documentcss#42]
I'm getting a warning in my terminal prompt stating that: `There is no @font tag. did you mean @body ?`. It is not giving a line number to fix the warning. The only thing I can think that is causing it is that I am defining LESS variables for fonts. Below is a sample of the LESS code I am using:

`@font-family-sans-serif:  'Roboto', sans-serif;'

How would I fix this?

**Comment by herrjosua** [comment]
I found the issue, right after I posted my question/comment. I had an inline comment between two of my font LESS variables. Removing the comment resolve the issue.

**Comment by lkodai** [comment]
If you'd like to create comments with `@` in them, you can escape it with an additional `@`. 

So it would look like `@@font-family-sans-serif` in the comment in the code, but will properly render as just "@font-family-sans-serif" in your docs.
