### ISSUE TITLE
"Color Palette" demo is not showing correctly

### ISSUE THREAD

**Issue by adrifolio** [bitovi/documentcss#9]
The "color palette" seems to be missing some styles. Currently there is not enough padding around each color and the color values and variables names are overlapping.

http://documentcss.com/examples/styles/variables.less.html

![screen shot 2015-05-04 at 9 07 38 am](https://cloud.githubusercontent.com/assets/950214/7454879/7f829098-f23d-11e4-894d-2a010ade1c6f.png)

This is how they should display:
![screen shot 2015-05-04 at 9 09 34 am](https://cloud.githubusercontent.com/assets/950214/7454883/891fe36c-f23d-11e4-9931-706265ed3260.png)

**Comment by ramblinjan** [comment]
Closed by 682965e26557584e96896c500adcd36377ad07d8
